const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'C:/Users/tlogin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname === '/' ? '/index.html' : new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml'})[path.extname(file)] || 'application/json');res.end(data);});});
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  const {default:worker}=await import('../worker/src/index.js');
  const {env,db}=require('./d1.cjs')();
  try{
    const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    page.on('dialog',d=>d.accept());
    await page.route('https://**/*',r=>r.abort());
    await page.goto(url);await page.waitForSelector('#nextStop h2');
    assert.equal(await page.locator('#syncEndpoint').count(),1);
    const initial=await page.evaluate(()=>JSON.parse(JSON.stringify(TripApp.trip)));
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.locator('#nextStop [data-status]').click();
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items[0].status),'current');
    await page.reload();assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items[0].status),'current');
    await page.locator('[data-view="more"]').click();await page.locator('[data-go="edit"]').click();
    await page.locator('#itemEditor details').first().locator('summary').click();
    await page.locator('#itemEditor [data-k="parking"]').first().fill('測試停車場 P7');
    await page.locator('#itemEditor [data-k="driveMinutes"]').first().fill('38');
    await page.locator('#itemEditor [data-k="stayMinutes"]').first().fill('90');
    await page.locator('#itemEditor [data-k="critical"]').first().check();
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items[0].driveMinutes),38);
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('#itemEditor details').first().locator('summary').click();
    const movedName=await page.evaluate(()=>TripApp.trip.days[0].items[0].name);
    await page.locator('[data-drag-item="0"]').dragTo(page.locator('[data-item-index="1"] .ed-head'));
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items[1].name),movedName);
    await page.setViewportSize({width:390,height:844});
    await page.locator('[data-view="plan"]').click();await page.locator('[data-route="map"]').click();assert.equal(await page.locator('#routeMap').isVisible(),true);
    await page.locator('[data-route="timeline"]').click();await page.locator('#planTimeline details summary').first().click();
    await page.evaluate(()=>TripApp.renderAll());assert.equal(await page.locator('#planTimeline details').first().evaluate(el=>el.open),true);
    await page.locator('[data-view="money"]').click();await page.locator('[data-amount="1000"]').click();await page.selectOption('#expCategory','ETC');await page.locator('#expForm button[type="submit"]').click();
    assert.match(await page.locator('#drivingCosts').innerText(),/1,000/);
    await page.locator('[data-quick="item"]').click();await page.locator('#quickName').fill('新景點測試');await page.locator('#quickForm button[type="submit"]').click();
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items.at(-1).name),'新景點測試');
    await page.locator('[data-quick="note"]').click();await page.locator('#quickNote').fill('明天記得帶雨具');await page.locator('#quickForm button[type="submit"]').click();
    assert.match(await page.evaluate(()=>TripApp.trip.days[0].notes),/明天記得帶雨具/);
    await page.evaluate(()=>{const t=structuredClone(TripApp.trip);t.startDate=TripCore.localTime(t.timeZone).date;t.days[0].items=[{name:'現在站',time:'00:00',stayMinutes:0,status:'current'},{name:'下一站',time:'10:00',driveMinutes:30}];TripApp.setTrip(t);});
    await page.locator('[data-view="today"]').click();assert.equal(await page.locator('#delayPanel').isVisible(),true);
    await page.locator('[data-delay="shift"]').click();assert.equal(await page.locator('#delayPanel').isVisible(),false);
    await page.screenshot({path:path.join(root,'tests/mobile.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1000});await page.locator('[data-view="plan"]').click();await page.locator('[data-route="timeline"]').click();
    await page.screenshot({path:path.join(root,'tests/desktop.png'),fullPage:true});
    await page.evaluate(()=>navigator.serviceWorker.ready);
    await page.reload();await page.context().setOffline(true);await page.reload();
    assert.equal(await page.locator('#nextStop h2').count(),1);
    assert.match(await page.locator('#networkState').innerText(),/離線/);
    await page.context().setOffline(false);
    await page.route('https://api.open-meteo.com/**',r=>r.fulfill({json:{daily:{temperature_2m_max:[24],precipitation_probability_max:[85],wind_speed_10m_max:[18]}}}));
    await page.evaluate(()=>{const t=structuredClone(TripApp.trip);t.days[0].items[0].lat=26.2;t.days[0].items[0].lng=127.7;t.days[0].items[0].outdoor=true;t.days[0].items[0].rainPlan='室內美術館';TripApp.setTrip(t);});
    await page.waitForFunction(()=>document.querySelector('#weatherInfo').textContent.includes('85%'));
    assert.match(await page.locator('#daySummary').innerText(),/室內美術館/);
    await page.route('https://sync.example.com/api/**',async r=>{
      const req=r.request();
      if(req.url().includes('/api/rate'))return r.fulfill({json:{rate:0.22,source:'test'}});
      const response=await worker.fetch(new Request(req.url(),{method:req.method(),headers:req.headers(),body:['GET','HEAD'].includes(req.method())?undefined:req.postData()}),env);
      return r.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:await response.text()});
    });
    await page.locator('[data-view="more"]').click();await page.locator('#syncAdvanced summary').first().click();
    await page.locator('#syncEndpoint').fill('https://sync.example.com');await page.locator('#syncCreate').click();
    await page.waitForFunction(()=>TripSync.version===1);
    await page.evaluate(()=>{const t=structuredClone(TripApp.trip);t.days[0].stay.reservationNo='private-test';TripApp.setTrip(t);});
    await page.waitForFunction(()=>TripSync.version===2);
    assert.equal(JSON.parse(db.prepare('SELECT trip FROM trips').get().trip).days[0].stay.reservationNo,undefined);
    await page.reload();await page.waitForFunction(()=>TripSync.status.state==='ok');
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].stay.reservationNo),'private-test');
    assert.equal(await page.evaluate(()=>TripSync.version),2);
    await page.context().setOffline(true);
    await page.evaluate(()=>{const t=structuredClone(TripApp.trip);t.days[0].notes='離線修改必須保留';TripApp.setTrip(t);});
    await page.reload();assert.equal(await page.evaluate(()=>TripApp.trip.days[0].notes),'離線修改必須保留');
    await page.context().setOffline(false);await page.reload();await page.waitForFunction(()=>TripSync.version===3);
    assert.equal(JSON.parse(db.prepare('SELECT trip FROM trips').get().trip).days[0].notes,'離線修改必須保留');
    const shared=await page.evaluate(()=>TripSync.shareUrl());
    const ownerConfig=await page.evaluate(()=>localStorage.getItem('tripSync'));
    await page.goto(shared+'#edit');await page.waitForFunction(()=>TripSync.status.state==='ok');
    assert.equal(await page.locator('#view-edit').isVisible(),false);assert.equal(await page.locator('[data-status]').count(),0);
    assert.equal(await page.evaluate(()=>TripSync.canEdit()),false);
    assert.equal(await page.evaluate(()=>localStorage.getItem('tripSync')),ownerConfig);
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].stay.reservationNo),undefined);
    await page.goto(url);await page.waitForFunction(()=>TripSync.status.state==='ok');
    await page.evaluate(()=>TripSync.disconnect());
    await page.evaluate(()=>TripApp.setTrip({title:'空白測試',days:[]}));
    await page.locator('[data-view="today"]').click();assert.match(await page.locator('#nextStop').innerText(),/先安排/);
    await page.evaluate(t=>TripApp.setTrip(t),initial);
    await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'tests/mobile.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1000});await page.locator('[data-view="plan"]').click();await page.screenshot({path:path.join(root,'tests/desktop.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('PASS mobile layout, status persistence, editing, route view, expense totals, delay, desktop, offline reload, weather rain alert, sync publication/privacy/reload, empty trip, read-only');
  } finally{await browser.close();server.close();db.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
