const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'C:/Users/tlogin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
let worker,env,adminToken;
const asset=async request=>{
  let pathname=decodeURIComponent(new URL(request.url).pathname).replace(/^\/admin\//,'/');
  if(pathname==='/')pathname='/index.html';
  const file=path.join(root,pathname);
  if(!file.startsWith(root+path.sep))return new Response(null,{status:403});
  try{return new Response(await fs.promises.readFile(file),{headers:{'content-type':({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml'})[path.extname(file)] || 'application/json'}});}
  catch(_){return new Response(null,{status:404});}
};
const server=http.createServer(async(req,res)=>{
  try{
    const url=`http://${req.headers.host}${req.url}`,pathname=new URL(url).pathname;
    const chunks=[];for await(const chunk of req)chunks.push(chunk);
    const headers={...req.headers};
    if(pathname.startsWith('/admin/'))headers.cookie=adminToken;
    const request=new Request(url,{method:req.method,headers,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)});
    const response=pathname.endsWith('/api/rate')?Response.json({rate:0.22,source:'test'}):pathname.startsWith('/admin/')||pathname.startsWith('/api/')?await worker.fetch(request,env):await asset(request);
    res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));
  }catch(error){res.writeHead(500);res.end(error.message);}
});
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  worker=(await import('../worker/src/index.js')).default;
  const database=require('./d1.cjs')(),db=database.db;
  const auth=await require('./auth.cjs')();
  env={...database.env,...auth.env,ASSETS:{fetch:asset}};
  adminToken=(await auth.login(worker,env,url)).cookie;
  const adminUrl=url+'/admin/';
  try{
    const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    page.on('dialog',d=>d.accept());
    await page.route('https://**/*',r=>r.abort());
    await page.goto(url);await page.waitForSelector('#nextStop h2');
    assert.equal(await page.evaluate(()=>TripSync.readOnly()),false);
    assert.equal(await page.evaluate(()=>TripSync.canEdit()),false);
    await page.locator('[data-view="more"]').click();
    assert.equal(await page.locator('#syncAdvanced').isVisible(),false);
    await page.locator('[data-go="edit"]').first().click();
    await page.locator('#setDest').selectOption('tokyo');
    await page.locator('#setStart').fill('2027-05-01');
    await page.locator('#setEnd').fill('2027-05-04');
    await page.locator('#setApply').click();
    assert.equal(await page.evaluate(()=>TripApp.trip.destId),'tokyo');
    assert.equal(await page.evaluate(()=>TripApp.trip.days.length),4);
    assert.ok(await page.evaluate(()=>TripApp.trip.days.every(day=>day.items.length>0)));
    const personalTrip=await page.evaluate(()=>JSON.stringify(TripApp.trip));
    await page.evaluate(()=>localStorage.setItem('tripSync',JSON.stringify({endpoint:'https://sync.example.com',code:'stale-code'})));
    await page.reload();
    assert.equal(await page.evaluate(()=>JSON.stringify(TripApp.trip)),personalTrip);
    assert.equal(await page.evaluate(()=>TripSync.enabled()),false);
    assert.equal(await page.evaluate(async()=>{try{await TripSync.createTrip(TripApp.trip);return false;}catch(error){return error.message.includes('管理入口');}}),true);
    const visitor=await browser.newPage();
    await visitor.route('https://**/*',r=>r.abort());
    await visitor.goto(url);
    assert.notEqual(await visitor.evaluate(()=>TripApp.trip.destId),'tokyo');
    await visitor.close();
    await page.evaluate(()=>localStorage.removeItem('tripSync'));
    await page.goto(adminUrl);await page.waitForSelector('#nextStop h2');
    assert.equal(await page.locator('#syncEndpoint').count(),1);
    const initial=await page.evaluate(()=>JSON.parse(JSON.stringify(TripApp.trip)));
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.locator('#nextStop [data-status]').click();
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items[0].status),'current');
    await page.reload();assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items[0].status),'current');
    await page.locator('[data-view="more"]').click();await page.locator('[data-go="edit"]').click();
    await page.locator('#itemEditor details').first().locator('summary').click();
    await page.locator('#itemEditor [data-k="parking"]').first().fill('測試停車場 P7');
    await page.locator('#itemEditor [data-k="driveMinutes"]').first().fill('38');
    await page.locator('#itemEditor [data-k="stayMinutes"]').first().fill('90');
    await page.locator('#itemEditor [data-k="critical"]').first().check();
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items[0].driveMinutes),38);
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('#itemEditor details').first().locator('summary').click();
    const movedName=await page.evaluate(()=>TripApp.trip.days[0].items[0].name);
    await page.locator('[data-drag-item="0"]').dragTo(page.locator('[data-item-index="1"] .ed-head'));
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items[1].name),movedName);
    await page.setViewportSize({width:390,height:844});
    await page.locator('[data-view="plan"]').click();await page.locator('[data-route="map"]').click();assert.equal(await page.locator('#routeMap').isVisible(),true);
    await page.locator('[data-route="timeline"]').click();await page.locator('#planTimeline details summary').first().click();
    await page.evaluate(()=>TripApp.renderAll());assert.equal(await page.locator('#planTimeline details').first().evaluate(el=>el.open),true);
    await page.locator('[data-view="money"]').click();await page.locator('[data-amount="1000"]').click();await page.selectOption('#expCategory','ETC');await page.locator('#expForm button[type="submit"]').click();
    assert.match(await page.locator('#drivingCosts').innerText(),/1,000/);
    await page.locator('[data-quick="item"]').click();await page.locator('#quickName').fill('新景點測試');await page.locator('#quickForm button[type="submit"]').click();
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].items.at(-1).name),'新景點測試');
    await page.locator('[data-quick="note"]').click();await page.locator('#quickNote').fill('明天記得帶雨具');await page.locator('#quickForm button[type="submit"]').click();
    assert.match(await page.evaluate(()=>TripApp.trip.days[0].notes),/明天記得帶雨具/);
    await page.evaluate(()=>{const t=structuredClone(TripApp.trip);t.startDate=TripCore.localTime(t.timeZone).date;t.days[0].items=[{name:'現在站',time:'00:00',stayMinutes:0,status:'current'},{name:'下一站',time:'10:00',driveMinutes:30}];TripApp.setTrip(t);});
    await page.locator('[data-view="today"]').click();assert.equal(await page.locator('#delayPanel').isVisible(),true);
    await page.locator('[data-delay="shift"]').click();assert.equal(await page.locator('#delayPanel').isVisible(),false);
    await page.screenshot({path:path.join(root,'tests/mobile.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1000});await page.locator('[data-view="plan"]').click();await page.locator('[data-route="timeline"]').click();
    await page.screenshot({path:path.join(root,'tests/desktop.png'),fullPage:true});
    await page.route('https://api.open-meteo.com/**',r=>r.fulfill({json:{daily:{temperature_2m_max:[24],precipitation_probability_max:[85],wind_speed_10m_max:[18]}}}));
    await page.evaluate(()=>{const t=structuredClone(TripApp.trip);t.days[0].items[0].lat=26.2;t.days[0].items[0].lng=127.7;t.days[0].items[0].outdoor=true;t.days[0].items[0].rainPlan='室內美術館';TripApp.setTrip(t);});
    await page.waitForFunction(()=>document.querySelector('#weatherInfo').textContent.includes('85%'));
    assert.match(await page.locator('#daySummary').innerText(),/室內美術館/);
    await page.locator('[data-view="more"]').click();await page.locator('#syncAdvanced summary').first().click();
    await page.locator('#syncCreate').click();
    await page.waitForFunction(()=>TripSync.version===1);
    await page.evaluate(()=>{const t=structuredClone(TripApp.trip);t.days[0].stay.reservationNo='private-test';TripApp.setTrip(t);});
    await page.waitForFunction(()=>TripSync.version===2);
    assert.equal(JSON.parse(db.prepare('SELECT trip FROM trips').get().trip).days[0].stay.reservationNo,undefined);
    await page.reload();await page.waitForFunction(()=>TripSync.status.state==='ok');
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].stay.reservationNo),'private-test');
    assert.equal(await page.evaluate(()=>TripSync.version),2);
    await page.context().setOffline(true);
    await page.evaluate(()=>{const t=structuredClone(TripApp.trip);t.days[0].notes='離線修改必須保留';TripApp.setTrip(t);});
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].notes),'離線修改必須保留');
    await page.context().setOffline(false);await page.reload();await page.waitForFunction(()=>TripSync.version===3);
    assert.equal(JSON.parse(db.prepare('SELECT trip FROM trips').get().trip).days[0].notes,'離線修改必須保留');
    const shared=await page.evaluate(()=>TripSync.shareUrl());
    assert.equal(new URL(shared).origin,'https://okd8888.github.io');
    const ownerConfig=await page.evaluate(()=>localStorage.getItem('tripSync'));
    await page.route('https://sync.example.com/api/**',async route=>{
      const response=await worker.fetch(new Request(route.request().url()),env);
      return route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:await response.text()});
    });
    const sharedLocal=new URL(shared);sharedLocal.searchParams.set('api','https://sync.example.com');
    await page.goto(url+sharedLocal.search+'#edit');await page.waitForFunction(()=>TripSync.status.state==='ok');
    assert.equal(await page.locator('#view-edit').isVisible(),false);assert.equal(await page.locator('[data-status]').count(),0);
    assert.equal(await page.evaluate(()=>TripSync.canEdit()),false);
    assert.equal(await page.evaluate(()=>localStorage.getItem('tripSync')),ownerConfig);
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].stay.reservationNo),undefined);
    await page.locator('[data-view="more"]').click();
    await page.locator('#personalTrip').click();
    assert.equal(await page.evaluate(()=>JSON.stringify(TripApp.trip)),personalTrip);
    assert.equal(await page.evaluate(()=>TripSync.enabled()),false);
    await page.goto(url+sharedLocal.search);await page.waitForFunction(()=>TripSync.status.state==='ok');
    await page.evaluate(()=>navigator.serviceWorker.ready);
    await page.reload();await page.context().setOffline(true);await page.reload();
    assert.equal(await page.locator('#nextStop h2').count(),1);
    assert.match(await page.locator('#networkState').innerText(),/離線/);
    assert.equal(await page.locator('[data-status]').count(),0);
    await page.context().setOffline(false);
    await page.goto(adminUrl);await page.waitForFunction(()=>TripSync.status.state==='ok');
    const originalCode=await page.evaluate(()=>TripSync.config.code);
    const otherResponse=await worker.fetch(new Request(url+'/admin/api/trip',{method:'POST',headers:{origin:url,'content-type':'application/json',cookie:adminToken},body:JSON.stringify({trip:{...initial,title:'第二份行程'}})}),env);
    const otherCode=(await otherResponse.json()).code;
    await page.goto(adminUrl+'?code='+otherCode);await page.waitForFunction(()=>TripSync.status.state==='ok');
    assert.equal(await page.evaluate(()=>TripApp.trip.title),'第二份行程');
    assert.equal(await page.evaluate(()=>TripApp.expenses.length),0);
    await page.goto(adminUrl+'?code='+originalCode);await page.waitForFunction(()=>TripSync.status.state==='ok');
    assert.equal(await page.evaluate(()=>TripApp.trip.days[0].stay.reservationNo),'private-test');
    await page.evaluate(()=>TripSync.disconnect());
    await page.evaluate(()=>TripApp.setTrip({title:'空白測試',days:[]}));
    await page.locator('[data-view="today"]').click();assert.match(await page.locator('#nextStop').innerText(),/先安排/);
    await page.evaluate(t=>TripApp.setTrip(t),initial);
    await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'tests/mobile.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1000});await page.locator('[data-view="plan"]').click();await page.screenshot({path:path.join(root,'tests/desktop.png'),fullPage:true});
    await page.route('**/admin/api/trip/**',route=>route.fulfill({status:401,json:{error:'請重新登入'}}));
    await page.evaluate(async code=>{TripSync.setConfig({code});try{await TripSync.pushTrip(TripApp.trip);}catch(_){}},originalCode);
    assert.equal(await page.evaluate(()=>TripSync.canEdit()),false);
    await page.locator('[data-view="more"]').click();
    assert.equal(await page.locator('#adminLogin').isVisible(),true);
    assert.deepEqual(errors,[]);
    console.log('PASS mobile layout, status persistence, editing, route view, expense totals, delay, desktop, offline reload, weather rain alert, sync publication/privacy/reload, empty trip, read-only');
  } finally{await browser.close();server.close();db.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
